/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { MyTitleContext } from "./myTitleContext";

class MyTitle extends MyTitleContext {
  // Operation groups
  categoryApi: operations.CategoryApi;
  productApi: operations.ProductApiOperations;

  /**
   * Initializes a new instance of the MyTitle class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.MyTitleOptions) {
    super(options);
    this.categoryApi = new operations.CategoryApi(this);
    this.productApi = new operations.ProductApiOperations(this);
  }
}

// Operation Specifications

export {
  MyTitle,
  MyTitleContext,
  Models as MyTitleModels,
  Mappers as MyTitleMappers
};
export * from "./operations";
